### ISSUE TITLE
Cannot Access Perl Library

### ISSUE THREAD

**Issue by ddmarshall** [flathub/org.texstudio.TeXstudio#110]
With a fresh install of the TeXstudio flatpak I cannot generate documents using `latexmk`. I get the following error:
```
perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory.
```
This seems to be similar to (same as) issue #94. As suggested in that issue discussion a work-around is to manually override the `PER5LIB` and `LD_LIBRARY_PATH` variables. This allows `latexmk` to run (note the version number bump from 5.34).

I tested things with the following steps:
```
$ flatpak run --command=sh org.texstudio.TeXstudio
[📦 org.texstudio.TeXstudio app]$ latexmk
perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
[📦 org.texstudio.TeXstudio app]$ export PERL5LIB=/app/texlive/lib/perl5/site_perl/5.36.0/:/app/texlive/lib/perl5/5.36.0/
[📦 org.texstudio.TeXstudio app]$ export LD_LIBRARY_PATH=/app/texlive/lib/:/app/texlive/lib/perl5/5.36.0/x86_64-linux/CORE/[📦 org.texstudio.TeXstudio app]$ latexmk
Rc files read:
  /home/username/.latexmkrc
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.

Latexmk: No file name specified, and I couldn't find any
Use
   latexmk -help
to get usage information
```
I am not familiar with flatpaks to come up with an actual solution.

**Comment by mpanhans** [comment]
Anyone have ideas on how this perl library issue can be resolved? The issue had been fixed but it seems with a new TexStudio release the path has been broken again. I've confirmed the issue that used to occur with biber, and then was fixed, is now occuring again.  @Alexander-Wilms @jakobjakobson13

**Comment by Alexander-Wilms** [comment]
I'll try and see if there's away to automatically detect the perl version and use it in the environment variable

**Comment by Alexander-Wilms** [comment]
Should be fixed now

**Comment by mpanhans** [comment]
I updated the TexStudio flatpak on my system to check this, and unfortunately TexStudio can no longer find the latex distribution. I have the TeX Live Flatpak installed and up-to-date; previously that worked, but no longer. I tried re-installing TS from Flathub and the issue persists. 
I am guessing this new problem is related to the fix for perl versioning, but not certain.

**Comment by Alexander-Wilms** [comment]
Can you try this test build? https://github.com/flathub/org.texstudio.TeXstudio/pull/114

Once the build is done, the flathubbot will post a comment with a command to install it.
Run it with `flatpak run org.texstudio.TeXstudio//test`

**Comment by mpanhans** [comment]
Yes this test build appears to be working great. On my machine it has found the Tex Live distribution AND the perl libraries.

**Comment by mpanhans** [comment]
I think I spoke too soon. 
Indeed the missing latex distribution issue is resolved. But when I tried the test build in https://github.com/flathub/org.texstudio.TeXstudio/pull/114, I had my Tex Live Flatpak rolled back to a commit from August. And that does work perfectly fine. But now I am trying to use biber with the current Tex Live Flatpak, and I am getting the same missing perl library error again.
I will keep digging to see, but this may still be an open issue.

**Comment by jakobjakobson13** [comment]
@Alexander-Wilms: Have/Can the paths be passed via `texstudio --env=PATH=... $1` in `texstudio.sh`?

**Comment by mpanhans** [comment]
Confirming this issue is still open. I did a completely fresh install of both Tex Live and TexStudio, and the perl libraries are not found. Sorry about the bad info from earlier.

**Comment by mpanhans** [comment]
So the issue is that if one launches the application with `flatpak run org.texstudio.TeXstudio` then it will find the perl libraries. But if the application is launched by clicking the desktop icon or clicking on a relevant file, then TexStudio will not find the perl libraries.
This appears to be due to behavior of the `command:` argument in the flatpak manifest. See https://manpages.debian.org/testing/flatpak-builder/flatpak-manifest.5.en.html

> command (string)
> 
> The filename or path to the main binary of the application. Note that this is really just a single file, not a commandline. If you want to pass arguments, install a shell script wrapper and use that as the command.
> Also note that the command is used when the application is run via flatpak run, and does not affect what gets executed when the application is run in other ways, e.g. via the desktop file or D-Bus activation.

Of course it would be ideal to find the perl libraries regardless of how TexStudio is launched, but I have not come up with an idea yet on how to achieve that. Also this explains why I was getting inconsistent results before about whether this issue was resolved.

**Comment by jakobjakobson13** [comment]
Perhaps we can patch the desktop file to execute the bash script. I'll try it later.
